services:
  icvdb-torznab:
    build: .
    container_name: icvdb-torznab
    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - icvdb_data:/data

    environment:
      DB_AUTO_UPDATE: "true"
      DB_UPDATE_INTERVAL: "86400"

volumes:
  icvdb_data:
    name: icvdb_torznab_data