services:
  icvdb-torznab:
    image: ghcr.io/xbit18/violarr:latest
    container_name: icvdb-torznab
    restart: unless-stopped

    ports:
      - "8000:8000"

    volumes:
      - icvdb_data:/data

volumes:
  icvdb_data:
    name: icvdb_torznab_data